title: Visualización de Información
description: > # this means to ignore newlines until "baseurl:"
  Página para el curso Visualización de Información

github_username: puc-infovis

baseurl: /version-2024-1
page-perma: /version-2024-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: "assets"
    values:
      image: true
      
theme: jekyll-theme-dinky
